config/routes.rb
Rails.application.routes.draw do
  root 'foods#index'

  get '/foods', to: 'foods#index'
  get '/foods/new', to: 'foods#new'
  post '/foods', to: 'foods#create'
  delete '/foods', to: 'foods#destroy'

  get '/restaurants/new', to: 'restaurants#new'
  post '/restaurants', to: 'restaurants#create'

  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  delete '/sign_out', to: 'sessions#destroy'

  get '/users', to: 'users#new'
  post '/users', to: 'users#create'

  get '/cart_list', to: 'cart_items#show'
  post '/buy', to: 'cart_items#create'
  patch '/add_cart', to: 'cart_items#update'
  delete '/cart_item', to: 'cart_items#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :food
  belongs_to :user
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods
  accepts_nested_attributes_for :foods
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
  belongs_to :restaurant

  has_one_attached :image

  has_many :cart_items, dependent: :destroy
  has_many :users, through: :cart_items

  scope :of_category, -> (category_id) { where(category_id: category_id) }
  scope :of_restaurant, -> (restaurant_id) { where(restaurant_id: restaurant_id) }

  validate :acceptable_image

  def acceptable_image
    return unless image.attached?

    acceptables_types = ['image/jpeg', 'image/png']
    unless acceptables_types.include?(image.content_type)
      errors.add(:image, 'Arquivo deve ser no formado JPEG ou PNG')
    end
  end
end

app/models/locale.rb
class Locale < ApplicationRecord
  belongs_to :restaurant, optional: true
  belongs_to :user, optional: true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :foods

  has_one :locale
  accepts_nested_attributes_for :locale

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :restaurant, required: false

  has_many :cart_items
  has_many :foods, through: :cart_items

  has_one :locale
  accepts_nested_attributes_for :locale
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :set_cart_item, only: [:update, :destroy]

  def show
    @cart_items = CartItem.includes(:food)
    @cart_items = CartItem.where(user_id: helpers.current_user.id)

    @total_quantity = @cart_items.map {|cart_item| cart_item[:quantity]}.reduce(:+)
    #@total_value = @cart_items.map {|cart_item| (cart_item.dig :food, :value)}.reduce(:+)

    @total_value = 0.00
    @cart_items.each do |cart_item|
      @total_value += (cart_item.food.value * cart_item.quantity)
    end
  end

  def create
    @item = CartItem.new(cart_items_params)
    if @item.save!
      redirect_to foods_path
    end
  end

  def update
    if @cart_item.update!(cart_items_params)
      redirect_to cart_list_path
    end
  end

  def destroy
    @cart_item.destroy
    redirect_to cart_list_path
  end


  private
    def set_cart_item
      @cart_item = CartItem.find(params[:id])
    end

    def cart_items_params
      params.require(:cart_items).permit(:food_id, :user_id, :quantity)
    end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :get_categories, only: [:index, :new]
  before_action :set_food, only: [:destroy]

  def index
    @foods = Food.includes(restaurant: :locale)

    if helpers.logged_in? && !helpers.current_user.restaurant.nil?
      @foods = Food.of_restaurant(helpers.current_user.restaurant.id)
    end

    if params[:category_id]
      @foods = @foods.of_category(params[:category_id])
    end

    if helpers.logged_in?
      @cart_items = CartItem.where(user_id: helpers.current_user.id)
      @quantity_items = @cart_items.map {|cart_item| cart_item[:quantity]}.reduce(:+)
    end
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    if @food.save!
      redirect_to foods_path
    end
  end

  def destroy
    if @food.destroy!
      redirect_to foods_path
    end
  end

  private
    def food_params
      params.require(:food).permit(:description, :value, :image_url, :image, :restaurant_id, :category_id)
    end

    def get_categories
      @categories = Category.all
    end

    def set_food
      @food = Food.find(params[:id])
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def new
    @restaurant = Restaurant.new
    @restaurant.build_locale
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to foods_path
    end
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:description, :user_id, locale_attributes: [:id, :city, :state, :street, :number])
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(email: session_params[:email])

    if @user && @user.password == session_params[:password]
      helpers.sign_in
      redirect_to foods_path
    else
      respond_to do |format|
        format.html { render :new }
      end
    end
  end

  def destroy
    helpers.sign_out
    redirect_to foods_path
  end

  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    @user.build_locale
  end

  def create
    @user = User.new(user_params)
    if @user.save
      helpers.sign_in
      redirect_to foods_path
    end
  end

  private
    def user_params
      params.require(:user).permit(:admin, :description, :email, :password, locale_attributes: [:id, :city, :number, :state, :street])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include SessionsHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
  def number_to_currency_br(number)
    number_to_currency(number, :unit => 'R$', :separator => ',', :delimiter => '.')
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in
    session[:user_id] = @user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cart_items/_header.html.erb
<header class="header">
  <div>
    <h1>Olá, <%= current_user.description %></h1>
    <%= link_to  "Voltar", root_path %>
  </div>

  <p>Essas são suas compras</p>
</header>

app/views/cart_items/show.html.erb
<div class="container">
  <%= render "header" %>

  <% if @cart_items.length == 0 %>
    <p>Você ainda não comprou nada, :(</p>
  <% else %>
    <main class="cart_box">
      <div class="cart_item">
        <strong>Imagem</strong>
        <strong>Produto</strong>
        <strong>Valor</strong>
        <strong>Qntd</strong>
      </div>

      <% @cart_items.each do |cart_item| %>
        <div class="cart_item">
          <%= image_tag cart_item.food.image, width: "150" %>
          <p><%= cart_item.food.description %></p>
          <strong><%= number_to_currency_br(cart_item.food.value * cart_item.quantity) %></strong>

          <div>
            <p><%= cart_item.quantity %></p>
            <%= button_to '+', add_cart_path, params: {:id => cart_item.id, :cart_items => {:food_id => cart_item.food_id, :user_id => cart_item.user_id, :quantity => cart_item.quantity + 1}}, :method => :patch, :disabled => cart_item.quantity == 10, :class => "plus" %>
            <%= button_to '-', add_cart_path, params: {:id => cart_item.id, :cart_items => {:food_id => cart_item.food_id, :user_id => cart_item.user_id, :quantity => cart_item.quantity - 1}}, :method => :patch, :disabled => cart_item.quantity == 1, :class => "sub" %>
          </div>
          <%= button_to "X", cart_item_path, params: {:id => cart_item.id}, :method => :delete, data: {confirm: 'Tem certeza?'} %>
        </div>
      <% end %>

      <div class="cart_item">
        <strong></strong>
        <strong></strong>
        <strong><%= number_to_currency_br(@total_value) %></strong>
        <%= @total_quantity %>
      </div>
    </main>
  <% end %>
</div>

app/views/foods/_form.html.erb
<%= form_for @food do |form| %>
  <div>
    <%= form.label "Nome" %>
    <%= form.text_field :description %>
  </div>
  <div>
    <%= form.label "Valor" %>
    <%= form.text_field :value %>
  </div>
  <div>
    <%= form.label "Imagem" %>
    <%= form.file_field :image %>
  </div>
  <%= hidden_field_tag "food[restaurant_id]", "#{current_user.restaurant.id}" %>
  <div>
    <%= form.label "Categoria" %>
    <%= form.collection_select(:category_id, @categories, :id, :description) %>
  </div>

  <%= form.submit 'Cadastrar' %>
<% end %>

app/views/foods/_header.html.erb
<header class="header">
  <div>
    <h1>Comidas</h1>
    <% if logged_in? %>
      <%= link_to  "Sair", sign_out_path, method: "delete" %>
    <% else %>
      <%= link_to "Entrar", sign_in_path %>
    <% end %>
  </div>

  <% if logged_in? && !current_user.restaurant.nil? %>
    <p>Verifique seus produtos ou adicione novos</p>
    <%= link_to  "Cadastrar nova comida", foods_new_path %>
  <% elsif logged_in? && current_user.admin %>
    <p>Cadastre seu restaurante e alcance suas metas!</p>
    <%= link_to  "Cadastrar restaurante", restaurants_new_path %>
  <% else %>
    <p>Veja o que há disponível em sua região</p>
  <% end %>

  <% if logged_in? && !current_user.admin %>
    <%= link_to "CARRINHO (#{@quantity_items})", cart_list_path %>
  <% end %>
</header>

app/views/foods/index.html.erb
<div class="container">
  <%= render "header" %>

  <div class="menu">
    <% @categories.each do |category| %>
      <%= link_to foods_path(:category_id => category.id), :class => "menu_item" do %>
        <%= image_tag category.image_url, size: "25x25" %>
        <%= category.description %>
      <% end %>
    <% end %>
    <%= link_to  "Limpar", foods_path, :class => "menu_item" %>
  </div>

  <% if @foods.length == 0 %>
    <p>Nada disponível no momento, retorne mais tarde!</p>
  <% else %>
    <main class="food_box">
      <% @foods.each do |food| %>
        <div class="food_item">
          <div class="title">
            <h3><%= food.description %></h3>
            <% if (logged_in? && !current_user.restaurant.nil?) && current_user.id == food.restaurant.user.id %>
              <%= button_to "X", foods_path, params: {:id => food.id}, :method => :delete, data: {confirm: 'Tem certeza?'} %>
            <% end %>
          </div>

          <%= image_tag food.image %>

          <div class="food_info">
            <div>
              <span><%= food.restaurant.description %></span>
              <p><%= food.restaurant.locale.street %>, <%= food.restaurant.locale.number %></p>
              <p><%= food.restaurant.locale.city %> - <%= food.restaurant.locale.state %></p>
            </div>

            <div class="info_shop">
              <strong><%= number_to_currency_br(food.value) %></strong>

              <% if logged_in? && current_user.restaurant.nil? %>
                <%= button_to 'COMPRAR', buy_path, params: {:cart_items => {:food_id => food.id, :user_id => current_user.id, :quantity => 1}}, :method => :post  %>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>
    </main>
  <% end %>
</div>

app/views/foods/new.html.erb
<% if !logged_in? || current_user.restaurant.nil? %>
  <% controller.redirect_to root_path %>
<% else %>
  <%= render "form",  restaurant: @restaurant %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IFood</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1" />

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |form| %>
  <div>
    <%= form.label :description, "Nome" %>
    <%= form.text_field :description %>
  </div>

  <%= hidden_field_tag "restaurant[user_id]", "#{current_user.id}" %>

  <%= form.fields_for :locale do |builder| %>
    <div>
      <%= builder.label :state, "Estado" %>
      <%= builder.text_field :state, maxlength: 2 %>
    </div>

    <div>
      <%= builder.label :city, "Cidade" %>
      <%= builder.text_field :city %>
    </div>

    <div>
      <%= builder.label :street, "Rua" %>
      <%= builder.text_field :street %>
    </div>

    <div>
      <%= builder.label :number, "Número" %>
      <%= builder.text_field :number, maxlength: 5 %>
    </div>
  <% end %>

  <p><%= form.submit 'Cadastrar' %></p>
<% end %>

app/views/restaurants/new.html.erb
<% if !logged_in? %>
  <% controller.redirect_to root_path %>
<% else %>
  <%= render 'form', restaurant: @restaurant %>
<% end %>

app/views/users/_form.html.erb
<%= form_for @user do |form| %>
  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :description %>
  </div>
  <div class="field">
    <%= form.label :Email %>
    <%= form.email_field :email %>
  </div>
  <div class="field">
    <%= form.label :Senha %>
    <%= form.password_field :password %>
  </div>

  <%= form.fields_for :locale do |builder| %>
    <div class="field">
      <%= builder.label :Estado %>
      <%= builder.text_field :state %>
    </div>

    <div class="field">
      <%= builder.label :Cidade %>
      <%= builder.text_field :city %>
    </div>

    <div class="field">
      <%= builder.label :Rua %>
      <%= builder.text_field :street %>
    </div>

    <div class="field">
      <%= builder.label :Número %>
      <%= builder.text_field :number %>
    </div>
  <% end %>

   <div>
    Dono de estabelecimento?<br />
    <%= form.radio_button :admin, true %> Sim
    <%= form.radio_button :admin, false %> Não <br />
  </div>

  <p><%= form.submit "Cadastrar" %></p>
<% end %>

app/views/users/new.html.erb
<%= render "form", user: @user %>